version: '3'
services:
  related_text_searcher:
    container_name: related_text_searcher
    build:
      context: ./
    ports:
      - 5000:5000
    volumes:
      - .:/related_text_searcher
    working_dir: /related_text_searcher
    tty: true
    # platform: linux/amd64